/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.caketuzz;

import com.caketuzz.model.Societe;
import com.caketuzz.model.TresorPublic;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {

        TresorPublic tresorPublic = TresorPublic.getInstance();

        Societe[] societes = Societe.loadData("societes.json");

        // Dependency Injection
        for (Societe s : societes)
            tresorPublic.addSociete(s);

        tresorPublic.calculImpots(2019);
        tresorPublic.calculImpots(2018);

    }
}
